DROP TABLE IF EXISTS Pruefung;
DROP TABLE IF EXISTS Fragenloesung;
DROP TABLE IF EXISTS Frage;
DROP TABLE IF EXISTS Fragekatalog;
DROP TABLE IF EXISTS Themengebiet;
DROP TABLE IF EXISTS Modul;
DROP TABLE IF EXISTS Pruefer;
DROP TABLE IF EXISTS Student;
DROP TABLE IF EXISTS Musterloesung;

CREATE TABLE Musterloesung
(idMusterloesung INTEGER PRIMARY KEY,
Loesung VARCHAR(255) NOT NULL,
Niveau INTEGER );

CREATE TABLE Student
(Matrikelnr INTEGER PRIMARY KEY,
Nachname VARCHAR(45) NOT NULL,
Vorname VARCHAR(45) NOT NULL,
Semester INTEGER,
Studiengang VARCHAR(45));

CREATE TABLE Pruefer
(PersNr INTEGER PRIMARY KEY,
Nachname VARCHAR(45) NOT NULL,
Vorname VARCHAR(45) NOT NULL);

CREATE TABLE Modul
(Modulnr INTEGER PRIMARY KEY,
Bezeichnung VARCHAR(45) NOT NULL);

CREATE TABLE Themengebiet
(idThemengebiet INTEGER PRIMARY KEY,
Bezeichnung VARCHAR(45) NOT NULL,
Modul_fk INTEGER,
CONSTRAINT fk_Modul FOREIGN KEY (Modul_fk) REFERENCES Modul (Modulnr) ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE Fragekatalog
(idFragekatalog INTEGER PRIMARY KEY,
Modul_fk INTEGER,
CONSTRAINT fk_Modul2 FOREIGN KEY (Modul_fk) REFERENCES Modul (Modulnr) ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE Frage
(idFrage INTEGER PRIMARY KEY,
Fragestellung VARCHAR(255) NOT NULL,
Niveau INTEGER NOT NULL,
Punkte DOUBLE NOT NULL,
gestellt BOOLEAN,
Themengebiet_fk INTEGER,
Fragekatalog_fk INTEGER,
CONSTRAINT fk_Fragekatalog FOREIGN KEY (Fragekatalog_fk) REFERENCES Fragekatalog (idFragekatalog) ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT fk_Themengebiet FOREIGN KEY (Themengebiet_fk) REFERENCES Themengebiet (idThemengebiet) ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE Fragenloesung
(idFragenloesung INTEGER PRIMARY KEY,
Musterloesung_fk INTEGER,
Frage_fk INTEGER,
CONSTRAINT fk_Musterloesung FOREIGN KEY (Musterloesung_fk) REFERENCES Musterloesung (idMusterloesung) ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT fk_Frage FOREIGN KEY (Frage_fk) REFERENCES Frage (idFrage) ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE Pruefung
(idPruefung INTEGER PRIMARY KEY,
Bezeichnung VARCHAR(45) NOT NULL,
Note DOUBLE,
Fragekatalog_fk INTEGER,
Matrikelnr INTEGER,
PersNr INTEGER,
CONSTRAINT fk_Fragekatalog2 FOREIGN KEY (Fragekatalog_fk) REFERENCES Fragekatalog (idFragekatalog) ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT fk_PersNr FOREIGN KEY (PersNr) REFERENCES Pruefer (PersNr) ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT fk_Matrikelnr FOREIGN KEY (Matrikelnr) REFERENCES Student (Matrikelnr) ON DELETE CASCADE ON UPDATE CASCADE);

